import {test} from 'node:test';import assert from 'node:assert/strict';import worker,{validatePlan} from '../server/index.js';
const example=n=>({focus:'Functions',possibilities:[{title:'write one function',outcome:'A small working function',prerequisite:'Python editor',tasks:[{title:'Try',minutes:n,action:'Define add(a,b), return a+b and test two calls.',resourceId:'python-functions',resourceUse:'Read defining functions.'}]}]});
test('precise budgets across requested times',()=>{for(const n of [1,10,17,28,43,59,61,87,133,280,480,1439]){const p=validatePlan(example(n),n);assert.equal(p.possibilities[0].tasks.reduce((a,t)=>a+t.minutes,0),n)}});
test('expanded sessions can require a bounded set of possibilities',()=>{const raw={focus:'Practice',possibilities:Array.from({length:5},(_,i)=>({title:`practice ${i}`,outcome:'A bounded practice outcome',prerequisite:'A small setup',tasks:[{title:'Try',minutes:17,action:'Practice one concrete step.',resourceId:'',resourceUse:''}]}))};assert.equal(validatePlan(raw,17,5).possibilities.length,5);assert.throws(()=>validatePlan({...raw,possibilities:raw.possibilities.slice(0,4)},17,5));assert.throws(()=>validatePlan({...raw,possibilities:[...raw.possibilities,{title:'six',outcome:'outcome',prerequisite:'setup',tasks:[{title:'Try',minutes:17,action:'Practice one concrete step.',resourceId:'',resourceUse:''}]}]},17,5))});
test('rejects invalid allocations and malformed model output',()=>{assert.throws(()=>validatePlan(example(17),18));for(const n of [-1,0,2.5])assert.throws(()=>validatePlan(example(n),n));assert.throws(()=>validatePlan({},17))});
test('model cannot invent resource URLs',()=>{const x=example(17);x.possibilities[0].tasks[0].resourceId='https://evil.test';assert.equal(validatePlan(x,17).possibilities[0].tasks[0].resource,null)});
test('invalid requests never reach provider',async()=>{for(const input of [{interest:'',availableMinutes:17},{interest:'Python',availableMinutes:0},{interest:'Python',availableMinutes:1500}]){const r=await worker.fetch(new Request('https://unscroll.test/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),{});assert.equal(r.status,400)}});
test('cross-origin requests rejected',async()=>{const r=await worker.fetch(new Request('https://unscroll.test/api/plan',{method:'POST',headers:{Origin:'https://elsewhere.test','Content-Type':'application/json'},body:'{}'}),{});assert.equal(r.status,403)});
test('missing credentials fail honestly',async()=>{const r=await worker.fetch(new Request('https://unscroll.test/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({interest:'Python',availableMinutes:17})}),{});assert.equal(r.status,503)});
