const $=s=>document.querySelector(s),app=$('#app');
const state={total:342,index:0,screen:'intro',details:false,busy:false,interest:'',plans:[],planMinutes:0,focus:'',context:'',requestId:0,taskIndex:0};
const reduce=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const pill=(label,action)=>`<button class="pill" data-action="${action}"><span class="label">${[...label].map((c,i)=>`<span class="letter" style="--i:${i}">${c===' '?'&nbsp;':c}</span>`).join('')}</span></button>`;
function theme(colors){const root=document.documentElement;root.style.setProperty('--bg',colors[0]);root.style.setProperty('--fg',colors[1]);root.style.setProperty('--muted',colors[2]);root.style.setProperty('--accent',state.screen==='intro'?'#bf4b32':colors[2]);document.querySelector('meta[name="theme-color"]').content=colors[0]}
function intro(){state.screen='intro';state.details=false;theme(['#f5f4ef','#161714','#777a70']);$('#edit').hidden=true;app.innerHTML=`<section class="intro"><h1>How much time do you<br>spend on your phone?</h1><div class="picker"><div class="wheel" id="hours" role="spinbutton" tabindex="0" aria-label="Daily screen time hours" aria-valuemin="0" aria-valuemax="23"></div><span class="colon">:</span><div class="wheel" id="minutes" role="spinbutton" tabindex="0" aria-label="Daily screen time minutes" aria-valuemin="0" aria-valuemax="59"></div></div><div class="picker-labels"><span>HOURS</span><span>MINUTES</span></div>${pill('Find the possibility','start')}<p class="error" id="error" aria-live="polite"></p><div class="bottom-line">THE TIME WAS ALREADY THERE.</div></section>`;setupWheel('hours',24,Math.floor(state.total/60));setupWheel('minutes',60,state.total%60)}
async function transition(fn,colors,origin='50% 100%'){if(state.busy)return;state.busy=true;document.body.classList.add('transition-lock');const wash=$('#color-wash');if(reduce()){fn();state.busy=false;document.body.classList.remove('transition-lock');return}document.body.style.background=getComputedStyle(document.body).backgroundColor;app.classList.add('leaving');await new Promise(r=>setTimeout(r,230));wash.style.background=colors[0];wash.style.zIndex='3';const animation=wash.animate([{clipPath:`circle(0% at ${origin})`},{clipPath:`circle(150% at ${origin})`}],{duration:1000,easing:'cubic-bezier(.76,0,.24,1)',fill:'forwards'});await new Promise(r=>setTimeout(r,490));fn();app.classList.remove('leaving');wash.style.zIndex='1';await animation.finished;theme(colors);document.body.style.background='';animation.cancel();wash.style.clipPath=`circle(0% at ${origin})`;state.busy=false;document.body.classList.remove('transition-lock');if(state.screen==='story')$('#possibility-title')?.focus({preventScroll:true})}
app.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||state.busy)return;const action=b.dataset.action;b.classList.add('clicked');if(action==='start'){if(state.total<1){$('#error').textContent='Choose at least one minute.';b.classList.remove('clicked');return}state.index=0;await new Promise(r=>setTimeout(r,reduce()?0:300));transition(intention,['#f5f4ef','#161714','#777a70'])}else if(action==='next')navigate(1);else if(action==='previous')navigate(-1);else if(action==='details')showPlan();else if(action==='submit-interest')submitInterest();else if(action==='revise')intention();else if(action==='plan-back')story();else if(action==='begin-session')beginSession();else if(action==='finish-task')finishTask();else if(action==='pause-task')toggleClock();else if(action==='finish-session')finishSession();else if(action==='home-final')home()});
const home=()=>{if(!state.busy){cancelRequest();stopClock();transition(intro,['#f5f4ef','#161714','#777a70'],'50% 0%')}};$('#home').onclick=$('#edit').onclick=home;
let touchX=0,touchY=0;app.addEventListener('touchstart',e=>{touchX=e.changedTouches[0].clientX;touchY=e.changedTouches[0].clientY},{passive:true});app.addEventListener('touchend',e=>{if(state.screen!=='story'||state.busy)return;const dx=e.changedTouches[0].clientX-touchX,dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5){if(dx<0)navigate(1);else if(state.index>0)navigate(-1)}},{passive:true});document.addEventListener('keydown',e=>{if(state.screen==='story'&&!state.busy&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){if(e.key==='ArrowRight'){e.preventDefault();navigate(1)}else if(e.key==='ArrowLeft'&&state.index>0){e.preventDefault();navigate(-1)}else if(e.key==='Escape')home()}});
function setupWheel(id,count,value){const el=$('#'+id);el.innerHTML='<div class="wheel-pad"></div>'+Array.from({length:count},(_,i)=>`<button tabindex="-1" aria-hidden="true" data-value="${i}">${String(i).padStart(2,'0')}</button>`).join('')+'<div class="wheel-pad"></div>';el.scrollTop=value*74;let drag=null;const update=()=>{const v=Math.max(0,Math.min(count-1,Math.round(el.scrollTop/74)));el.setAttribute('aria-valuenow',v);el.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('selected',i===v));state.total=id==='hours'?v*60+state.total%60:Math.floor(state.total/60)*60+v;};el.addEventListener('scroll',update,{passive:true});el.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?count-1:Math.round(el.scrollTop/74)+(e.key==='ArrowDown'?1:-1);el.scrollTo({top:Math.max(0,Math.min(count-1,next))*74,behavior:'smooth'})}});el.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'){drag={y:e.clientY,top:el.scrollTop};el.setPointerCapture(e.pointerId);el.style.scrollSnapType='none'}});el.addEventListener('pointermove',e=>{if(drag)el.scrollTop=drag.top+drag.y-e.clientY});el.addEventListener('pointerup',()=>{if(drag){el.style.scrollSnapType='y mandatory';el.scrollTo({top:Math.round(el.scrollTop/74)*74,behavior:'smooth'});drag=null}});el.addEventListener('click',e=>{if(e.target.dataset.value)el.scrollTo({top:Number(e.target.dataset.value)*74,behavior:'smooth'})});update()}


const escapeHTML=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let loadingTimer=null,typingFrame=null;
let composing=false,requestController=null,clockInterval=null,clockEnd=0,clockLeft=0,clockRunning=false,lastInputAt=0;
function cancelRequest(){clearTimeout(loadingTimer);state.requestId++;requestController?.abort();requestController=null}
function intention(){state.screen='intention';$('#edit').hidden=false;theme(['#f5f4ef','#161714','#777a70']);app.innerHTML=`<section class="intention"><h1>What are you into right now?</h1><div class="writing-stage"><textarea id="intention-input" rows="2" maxlength="2000" aria-label="What are you into right now?" enterkeyhint="go" spellcheck="true" autocomplete="off"></textarea><div class="writing-mirror" aria-hidden="true"></div><div class="intention-caret" aria-hidden="true"></div></div><div id="routing-placeholder"></div><div class="intention-bottom"><span class="intention-note">${fmt(state.total)} to explore what matters to you.</span><button class="continue-intention" data-action="submit-interest" disabled>Continue</button></div><p class="request-error" id="request-error" role="status"></p></section>`;const input=$('#intention-input');input.value=state.interest;input.addEventListener('compositionstart',()=>{composing=true});input.addEventListener('compositionend',()=>{composing=false;inputUpdated(true)});input.addEventListener('beforeinput',e=>{if(e.inputType.startsWith('delete')&&!composing)deleteEcho()});input.addEventListener('input',()=>inputUpdated(!composing));input.addEventListener('click',()=>positionCaret());input.addEventListener('keyup',()=>positionCaret());input.addEventListener('select',()=>positionCaret());input.addEventListener('focus',()=>positionCaret());input.addEventListener('blur',()=>{$('.intention-caret')?.style.setProperty('opacity','0')});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!composing){e.preventDefault();submitInterest()}});inputUpdated(false);requestAnimationFrame(()=>{if(state.screen!=='intention')return;input.focus({preventScroll:true});input.setSelectionRange(input.value.length,input.value.length);positionCaret()})}
function syncMirror(){const input=$('#intention-input'),mirror=$('.writing-mirror');if(!input||!mirror)return null;mirror.textContent=input.value+'\u200b';return {input,mirror,node:mirror.firstChild}}
function textRect(index,end=index){const m=syncMirror();if(!m)return null;const range=document.createRange();range.setStart(m.node,Math.min(index,m.node.length-1));range.setEnd(m.node,Math.min(Math.max(index+1,end),m.node.length));const rect=range.getClientRects()[0];return rect?{rect,stage:$('.writing-stage').getBoundingClientRect()}:null}
function positionCaret(){const input=$('#intention-input'),caret=$('.intention-caret'),stage=$('.writing-stage');if(!input||!caret||state.screen!=='intention')return;const info=textRect(input.selectionStart);if(!info){stage.classList.remove('custom-caret');return}stage.classList.add('custom-caret');caret.style.height=info.rect.height+'px';caret.style.transform=`translate(${info.rect.left-info.stage.left}px,${info.rect.top-info.stage.top}px)`;caret.style.opacity=document.activeElement===input&&input.selectionStart===input.selectionEnd?'1':'0';if(document.activeElement===input){const bottom=window.visualViewport?window.visualViewport.height+window.visualViewport.offsetTop:innerHeight;if(info.rect.bottom>bottom-70)window.scrollBy({top:info.rect.bottom-bottom+100,behavior:reduce()?'instant':'smooth'})}}
function echoAt(index,char,deleting=false){if(reduce()||!char||/\s/.test(char))return;const info=textRect(index);if(!info)return;const echo=document.createElement('span');echo.className='typing-echo'+(deleting?' deleting':'');echo.setAttribute('aria-hidden','true');echo.dataset.index=index;echo.textContent=char;echo.style.left=(info.rect.left-info.stage.left)+'px';echo.style.top=(info.rect.top-info.stage.top)+'px';echo.style.lineHeight=info.rect.height+'px';$('.writing-stage').append(echo);echo.addEventListener('animationend',()=>echo.remove(),{once:true})}
function deleteEcho(){const input=$('#intention-input');if(input?.selectionStart)echoAt(input.selectionStart-1,input.value[input.selectionStart-1],true)}
function inputUpdated(animate){const input=$('#intention-input');if(!input)return;const previous=state.interest;state.interest=input.value;const stage=$('.writing-stage');stage.classList.toggle('medium',input.value.length>90&&input.value.length<=260);stage.classList.toggle('long',input.value.length>260);input.style.height='auto';input.style.height=Math.max(180,input.scrollHeight)+'px';$('.continue-intention').disabled=!input.value.trim();cancelAnimationFrame(typingFrame);typingFrame=requestAnimationFrame(()=>{refreshEchoes();positionCaret();if(animate&&input.value.length>previous.length){const count=Math.min(10,input.value.length-previous.length),end=input.selectionStart;for(let i=Math.max(0,end-count);i<end;i++)echoAt(i,input.value[i]);const now=performance.now(),fast=now-lastInputAt<130;lastInputAt=now;if(!reduce())$('.intention-caret')?.animate([{width:fast?'7px':'5px'},{width:'3px'}],{duration:190,easing:'ease-out'})}})}
window.visualViewport?.addEventListener('resize',()=>{if(state.screen==='intention')requestAnimationFrame(positionCaret)});window.addEventListener('resize',()=>{if(state.screen==='intention')inputUpdated(false)});

function refreshEchoes(){const input=$('#intention-input');if(!input)return;document.querySelectorAll('.typing-echo:not(.deleting)').forEach(e=>{const index=Number(e.dataset.index);if(input.value[index]!==e.textContent){e.remove();return}const info=textRect(index);if(info){e.style.left=(info.rect.left-info.stage.left)+'px';e.style.top=(info.rect.top-info.stage.top)+'px';e.style.lineHeight=info.rect.height+'px'}})}
function startLoading(){clearTimeout(loadingTimer);$('.intention h1').textContent='Your time, taking shape.';$('#routing-placeholder').innerHTML=`<div class="routing-sequence" role="status" aria-live="polite" aria-label="Time received. Shaping your plan."><div class="routing-context"><span>${fmt(state.total)}</span><p>${escapeHTML(state.interest)}</p></div><ol class="routing-steps"><li class="routing-step received"><span class="routing-dot" aria-hidden="true"></span><span class="received-label">Time received</span></li><li class="routing-connector first" aria-hidden="true"><span>↓</span></li><li class="routing-step shaping"><span class="routing-dot" aria-hidden="true"></span><span class="shaping-label">Shaping your plan</span></li><li class="routing-connector second" aria-hidden="true"><span>↓</span></li><li class="routing-step delivering"><span class="routing-dot" aria-hidden="true"></span><span>Ready for you</span></li></ol><p class="routing-reassurance">Turning your interest into a session that fits.</p></div>`;$('.intention-note').textContent='';loadingTimer=setTimeout(()=>{const note=$('.routing-reassurance');if(note&&state.screen==='routing')note.textContent='Still working on your session. Your words are safe here.'},18000);window.scrollTo({top:0,behavior:reduce()?'instant':'smooth'})}
function finishLoading(){clearTimeout(loadingTimer);const sequence=$('.routing-sequence');if(!sequence)return;sequence.classList.add('is-ready');sequence.setAttribute('aria-label','Your plan is ready.');$('.routing-reassurance').textContent='Your next possibility is ready.'}

function resizePlans(plans,oldTime,newTime){if(!plans.length||Math.abs(newTime-oldTime)>Math.max(10,oldTime*.2))return null;const copy=structuredClone(plans);for(const p of copy){let delta=newTime-oldTime;for(let i=p.tasks.length-1;i>=0&&delta<0;i--){const take=Math.min(-delta,p.tasks[i].minutes-1);p.tasks[i].minutes-=take;delta+=take}if(delta<0)return null;if(delta>0)p.tasks[p.tasks.length-1].minutes+=delta;p.tasks.forEach(t=>{t.action=t.action.replace(/\b\d+\s*(?:minutes?|mins?)\b/gi,'the allocated time')})}return copy}
async function submitInterest(){if(state.busy||state.screen==='routing')return;const interest=state.interest.trim();if(!interest){$('#intention-input')?.focus();return}const retained=interest===state.planInterest?resizePlans(state.plans,state.planMinutes,state.total):null;if(retained){state.plans=retained;const change=state.total-state.planMinutes;state.change=change?`${change>0?'+':''}${change} min · practice blocks adjusted.`:'';state.planMinutes=state.total;state.index=0;await transition(story,THEMES[0]);return}cancelRequest();const id=state.requestId;requestController=new AbortController();const controller=requestController;const timeout=setTimeout(()=>controller.abort(),95000);if(state.screen!=='intention')intention();state.screen='routing';$('.intention').classList.add('is-routing');$('#intention-input').readOnly=true;$('#intention-input').blur();$('.continue-intention').hidden=true;startLoading();$('#request-error').textContent='';try{const response=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({interest,availableMinutes:state.total,previousContext:state.context+(state.planInterest===interest&&state.plans.length?'\nPreviously suggested, not completed: '+state.plans[0].title:''),exclude:[]}),signal:requestController.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Please try again.');if(id!==state.requestId)return;if(!Array.isArray(data.possibilities)||data.possibilities.length<5)throw Error('We couldn’t shape this session. Please try again.');state.plans=data.possibilities.slice(0,10);state.focus=data.focus;state.planInterest=interest;state.planMinutes=state.total;state.index=0;state.change='';finishLoading();await transition(story,THEMES[0]);}catch(error){if(id!==state.requestId)return;state.screen='intention';clearTimeout(loadingTimer);$('.intention')?.classList.remove('is-routing');$('.intention h1').textContent='What are you into right now?';$('#intention-input').readOnly=false;$('.continue-intention').hidden=false;$('#routing-placeholder').innerHTML='';$('#request-error').textContent=error.name==='AbortError'?'This is taking longer than expected. Please try again.':error.message;$('.intention-note').textContent='Your words are still here.';}finally{clearTimeout(timeout);clearTimeout(loadingTimer)}}
function story(){state.screen='story';$('#edit').hidden=false;const p=state.plans[state.index];if(!p){intention();return}theme(THEMES[state.index%THEMES.length]);const hasNext=state.index<state.plans.length-1;app.innerHTML=`<section class="story" aria-label="Personalized possibility"><div class="story-top reveal"><span class="budget">${fmt(state.total)} of screen time. Reimagined.</span></div><div class="story-main"><p class="lead reveal">You could</p><h1 tabindex="-1" id="possibility-title">${(p.title.replace(/[.!?]+$/,'')+'.').split(' ').map((w,i)=>`<span class="word-wrap"><span class="word" style="--i:${Math.min(i,12)}">${escapeHTML(w)}</span></span>`).join('')}</h1><p class="estimate reveal"><strong>Planned focused time · ${fmt(state.total)}</strong>${state.change?'<br>'+escapeHTML(state.change):''}</p></div><div class="story-bottom with-action reveal"><button class="text-button" data-action="details">Use this time</button><div class="next-controls"><button class="previous" aria-label="Previous possibility" data-action="previous" ${state.index===0?'disabled':''}>‹</button>${hasNext?pill('Another possibility','next'):''}</div></div></section>`}
async function navigate(delta){if(state.busy)return;const index=state.index+delta;if(index<0||index>=state.plans.length)return;state.index=index;await transition(story,THEMES[index%THEMES.length],delta<0?'0% 50%':'100% 100%')}
function resourceHTML(resource){if(!resource)return '';let u;try{u=new URL(resource.url);if(u.protocol!=='https:')return ''}catch{return ''}return `<a class="resource-link" href="${escapeHTML(u.href)}" target="_blank" rel="noopener noreferrer">${escapeHTML(resource.title)}</a>${resource.use?`<p class="resource-use">${escapeHTML(resource.use)}</p>`:''}`}
function showPlan(){state.screen='plan';const p=state.plans[state.index];app.innerHTML=`<section class="plan-screen"><button class="plan-back" data-action="plan-back">Back</button><div class="plan-head"><h1>${escapeHTML(p.title)}</h1><div class="plan-total">${fmt(state.total)}</div></div><p class="plan-outcome">${escapeHTML(p.outcome)}</p>${p.prerequisite?`<p class="plan-outcome">You’ll need: ${escapeHTML(p.prerequisite)}</p>`:''}<div class="time-band" aria-label="Time allocated across ${p.tasks.length} tasks">${p.tasks.map((t,i)=>`<span style="flex:${t.minutes};--alpha:${1-i*.09};--i:${i}" title="${escapeHTML(t.title)}: ${fmt(t.minutes)}"></span>`).join('')}</div>${p.tasks.map(t=>`<article class="plan-task"><time>${fmt(t.minutes)}</time><div><h2>${escapeHTML(t.title)}</h2><p>${escapeHTML(t.action)}</p>${resourceHTML(t.resource)}</div></article>`).join('')}<div class="plan-bottom"><p>${fmt(state.total)} allocated exactly. Pace and outcomes vary.<br>${state.total>90?'Split this plan into separate sittings if you prefer.':''}</p>${pill('Begin this session','begin-session')}</div></section>`;window.scrollTo({top:0,behavior:'instant'})}
function stopClock(){clearInterval(clockInterval);clockInterval=null;clockRunning=false}
function beginSession(){stopClock();state.taskIndex=0;state.screen='focus';renderFocus(true)}
function renderFocus(reset){const p=state.plans[state.index],t=p.tasks[state.taskIndex];state.screen='focus';if(reset){clockLeft=t.minutes*60;clockEnd=Date.now()+clockLeft*1000;clockRunning=true}app.innerHTML=`<section class="plan-screen"><p class="focus-status">${escapeHTML(state.focus)}</p><div class="plan-head"><h1>${escapeHTML(t.title)}</h1></div><p class="session-instruction">${escapeHTML(t.action)}</p>${resourceHTML(t.resource)}<div class="focus-clock" id="focus-clock"></div><p class="focus-status" id="focus-status">One focused block. Go at your pace.</p><div class="plan-bottom"><button class="text-button" data-action="pause-task">Pause</button>${pill(state.taskIndex===p.tasks.length-1?'Finish session':'Complete this block','finish-task')}</div></section>`;updateClock();clearInterval(clockInterval);clockInterval=setInterval(updateClock,250);window.scrollTo({top:0,behavior:'instant'})}
function updateClock(){if(clockRunning)clockLeft=Math.max(0,Math.ceil((clockEnd-Date.now())/1000));const c=$('#focus-clock');if(c)c.textContent=`${String(Math.floor(clockLeft/60)).padStart(2,'0')}:${String(clockLeft%60).padStart(2,'0')}`;if(!clockLeft&&clockRunning){stopClock();if($('#focus-status'))$('#focus-status').textContent='Your time block is complete. Finish when you’re ready.'}}
function toggleClock(){if(clockRunning){updateClock();clockRunning=false}else{clockEnd=Date.now()+clockLeft*1000;clockRunning=true}const b=$('[data-action="pause-task"]');if(b)b.textContent=clockRunning?'Pause':'Resume'}
function finishTask(){stopClock();const p=state.plans[state.index];state.context=(state.context+'\nCompleted: '+p.tasks[state.taskIndex].title).slice(-1800);state.taskIndex++;if(state.taskIndex<p.tasks.length)renderFocus(true);else{state.screen='complete';app.innerHTML=`<section class="story"><div class="story-main"><p class="lead">${escapeHTML(state.focus)}</p><h1>The time was<br>already there.</h1><p class="estimate">You marked ${p.tasks.length} practice ${p.tasks.length===1?'block':'blocks'} complete.</p></div><div class="story-bottom">${pill('Back to home','home-final')}</div></section>`}}
function finishSession(){state.plans=[];state.interest='Continue '+state.focus+'.';intention()}
intro();
