// Focused-practice estimates curated for planning, not measured guarantees.
const SKILLS=[
{ name:'a Rubik’s cube',theme:0,need:'A standard 3×3 cube and a beginner-method guide.',steps:[[12,'make a white cross','Match the four white edges to their side centres.'],[45,'solve the first layer','Practice the white cross and insert the four corner pieces.'],[150,'solve a Rubik’s cube with a guide','Work through the beginner layer-by-layer method, then repeat a complete solve.'],[360,'practice a Rubik’s cube solve from memory','Rehearse the beginner method and review the steps that still need prompts.']]},
{ name:'German',theme:1,need:'Beginner German audio and a voice recorder.',steps:[[10,'say your first German phrases','Practice Hallo, Guten Tag, Danke and Bitte with a pronunciation model.'],[35,'introduce yourself in German','Practice your name, where you live and a simple greeting exchange.'],[100,'order a coffee in German','Rehearse a café dialogue: greeting, ordering, price and thanks.'],[240,'hold a short German introduction','Practice introductions, basic questions and a guided back-and-forth conversation.']]},
{ name:'the London System',theme:2,need:'A chessboard; familiarity with how the pieces move.',steps:[[15,'set up the London System','Place d4, Nf3 and Bf4, and identify a sensible development plan.'],[50,'play the opening moves of the London','Practice development against two common Black setups.'],[160,'practice three London System plans','Explore the e4 break, a kingside attack and central exchanges in model positions.'],[420,'build a beginner London repertoire','Study model games, play practice positions and review your opening decisions.']]},
{ name:'the flute',theme:3,need:'A transverse flute and a beginner embouchure demonstration.',steps:[[12,'try your first flute tone','Practice shaping the air stream on the headjoint; a clear tone may take repeated sessions.'],[40,'practice three notes on the flute','Work on a stable air stream and the fingerings for B, A and G.'],[130,'play a simple flute phrase','Practice a short B–A–G melody slowly, connecting the notes with steady breath.'],[330,'practice a first flute melody','Work through a short beginner melody, phrase by phrase, with steady rhythm.']]},
{ name:'Sudoku',theme:4,need:'A beginner Sudoku puzzle and a pencil.',steps:[[8,'spot your first Sudoku singles','Find cells with only one possible number using row, column and box constraints.'],[30,'solve an easy Sudoku step by step','Use naked and hidden singles; write down why each number must fit.'],[95,'spot Sudoku pairs and triples','Practice candidate elimination with naked pairs and a few guided triples.'],[220,'solve Sudoku with a small strategy toolkit','Practice singles, pairs and pointing candidates on a set of graded puzzles.']]},
{ name:'linear algebra',theme:5,need:'Paper and a pencil; basic arithmetic and algebra.',steps:[[12,'add vectors on a coordinate grid','Draw two 2D vectors and their sum using the tip-to-tail method.'],[40,'see what a dot product measures','Calculate several 2D dot products and connect them to direction and projection.'],[110,'use matrices to move a shape','Apply 2×2 matrices to rotate, scale and shear the corners of a triangle.'],[270,'solve systems with row reduction','Practice Gaussian elimination on 2×2 and 3×3 systems and check each solution.']]},
{ name:'the Scandinavian',theme:6,need:'A chessboard; familiarity with legal moves.',steps:[[15,'try the Scandinavian Defence','Explore 1. e4 d5, the central exchange and Black’s queen recapture.'],[55,'practice a Scandinavian setup','Study the Qa5 variation and develop Black’s minor pieces in model positions.'],[180,'prepare three Scandinavian responses','Practice responses to common White development choices and review tactical pitfalls.'],[390,'build a small Scandinavian repertoire','Annotate model games and test your plans in practice positions.']]},
{ name:'the Réti Opening',theme:7,need:'A chessboard; familiarity with legal moves.',steps:[[18,'try the Réti Opening','Explore Nf3, a kingside fianchetto and pressure on the centre.'],[65,'practice two Réti structures','Compare a c4 setup with a d4 transposition in sample positions.'],[190,'understand three Réti middlegame plans','Practice central breaks and piece placement in three typical pawn structures.'],[450,'build a starter Réti repertoire','Study model games and rehearse responses to several common Black setups.']]},
{ name:'the King’s Indian',theme:8,need:'A chessboard; familiarity with opening development.',steps:[[20,'set up the King’s Indian Defence','Practice Nf6, g6, Bg7 and d6 against a d4/c4 centre.'],[70,'understand the King’s Indian central breaks','Compare the ideas behind ...e5 and ...c5 in guided positions.'],[200,'practice three King’s Indian plans','Explore a closed centre, kingside pawn play and queenside counterplay.'],[480,'build a starter King’s Indian repertoire','Study model games, test typical structures and review your decisions.']]},
{ name:'Morse code',theme:9,need:'A Morse audio trainer.',steps:[[5,'recognize E and T in Morse code','Listen for a short dit and a longer dah; identify a small mixed sequence.'],[25,'recognize six Morse characters','Practice E, T, I, M, A and N as sounds rather than counting symbols.'],[90,'practice the Morse alphabet','Work through letter sounds in short, spaced listening drills.'],[260,'decode slow Morse practice messages','Practice a familiar set of letters and short words with a slow audio trainer.']]},
{ name:'origami',theme:10,need:'Square sheets of paper and a folding diagram.',steps:[[8,'fold an origami jumping frog','Follow a simple frog pattern and test how the final fold changes its jump.'],[30,'fold your first paper crane','Practice the bird base and follow a complete crane diagram.'],[90,'fold three precise origami models','Make a crane, a box and a lily, repeating difficult folds.'],[240,'create a small modular origami piece','Fold matching units and assemble a guided geometric model.']]},
{ name:'SQL',theme:11,need:'A browser-based SQL practice database.',steps:[[15,'ask a database your first question','Use SELECT and WHERE to retrieve a filtered set of rows.'],[50,'summarize data with SQL','Practice GROUP BY, COUNT and SUM on a small sample table.'],[140,'join two tables with SQL','Use INNER and LEFT JOIN and explain why unmatched rows differ.'],[320,'investigate a dataset using SQL','Combine joins, aggregates and subqueries to answer five concrete questions.']]},
{ name:'fingerstyle guitar',theme:12,need:'An acoustic guitar; familiarity with holding it safely.',steps:[[15,'try a fingerpicking pattern','Practice thumb–index–middle–ring slowly on open strings.'],[55,'fingerpick a two-chord loop','Keep a steady pattern while moving between two comfortable chords.'],[170,'play a short fingerstyle phrase','Practice a simple melody with alternating bass notes in small sections.'],[400,'practice a beginner fingerstyle arrangement','Work through a short arrangement section by section, then connect the phrases.']]},
{ name:'the night sky',theme:13,need:'A sky map matched to your location; a clear sky for observation.',steps:[[10,'read a map of tonight’s sky','Match compass directions and identify one currently visible constellation.'],[35,'find three constellations','Use a location-specific sky map to trace three visible star patterns.'],[100,'plan your first stargazing session','Identify visible targets and practice star-hopping on a map before observing.'],[250,'build a small observing journal','Plan and document several visible targets over separate clear evenings.']]},
{ name:'beatboxing',theme:14,need:'A voice recorder and a beginner sound demonstration.',steps:[[7,'try a beatbox kick drum','Practice a crisp, unvoiced B sound in short bursts.'],[25,'combine a kick and hi-hat','Alternate a B kick with a ts hi-hat at a comfortable tempo.'],[85,'practice a basic beatbox groove','Combine kick, hi-hat and snare into a slow four-beat pattern.'],[210,'build a short beatbox routine','Connect two grooves and a simple fill, then record and review your timing.']]},
{ name:'knots',theme:15,need:'A short length of practice rope; not for safety-critical use.',steps:[[6,'tie a figure-eight knot','Tie, inspect and untie a stopper knot several times.'],[22,'tie a bowline with a guide','Follow a diagram and check the loop and tail placement.'],[65,'practice four useful knots','Rehearse a figure-eight, bowline, clove hitch and sheet bend.'],[160,'choose knots for everyday tasks','Practice appropriate knots for joining cord, making a loop and securing light objects.']]},
{ name:'binary numbers',theme:16,need:'Paper and a pencil.',steps:[[5,'count to fifteen in binary','Use four columns with place values 8, 4, 2 and 1.'],[20,'convert small numbers to binary','Practice converting decimal values to eight-bit binary and back.'],[60,'add numbers in binary','Practice carrying bits and verify your answers in decimal.'],[150,'build a paper logic circuit','Use truth tables to connect AND, OR and XOR gates into a half-adder.']]},
{ name:'a tiny animation',theme:17,need:'A browser-based CSS editor.',steps:[[10,'animate a dot with CSS','Use a keyframe to move a dot between two positions.'],[35,'make a convincing bouncing ball','Combine squash, stretch and timing in a simple CSS animation.'],[105,'animate a seamless loading loop','Coordinate repeated shapes and phase offsets into a continuous loop.'],[260,'build an interactive motion study','Connect a button, changing states and reduced-motion support in a tiny webpage.']]}
];
const THEMES=[["#101110", "#f5f4ef", "#a7aaa3"], ["#a8dbf3", "#113b65", "#345d7e"], ["#e9f27e", "#263d20", "#536543"], ["#e9b7d1", "#59273f", "#704058"], ["#ed663f", "#311c16", "#3c211a"], ["#e3e1f6", "#342c65", "#635b84"], ["#214d42", "#edf3d5", "#bbcfad"], ["#f4d4a0", "#543717", "#785125"], ["#571e32", "#ffe3cf", "#dfa4b1"], ["#d0eee2", "#174b48", "#476b61"], ["#f5eedb", "#5c492c", "#786747"], ["#243b76", "#f3ebcc", "#b7c8ed"], ["#b8442e", "#fff1d5", "#ffebc9"], ["#181d3e", "#f1e9ff", "#bdb8df"], ["#efb728", "#382a13", "#5d4721"], ["#bac9a6", "#293b26", "#405337"], ["#ddd5c9", "#393735", "#5e5850"], ["#654589", "#fcf0ff", "#e3ccef"]];
function fmt(n){return n<60?`${n} min`:`${Math.floor(n/60)}h${n%60?' '+String(n%60).padStart(2,'0')+'m':''}`}
function possibilities(time){return SKILLS.map((s,i)=>{const step=s.steps.filter(m=>m[0]<=time).at(-1)||s.steps[0];return {...s,index:i,minutes:step[0],title:step[1],description:step[2],days:Math.ceil(step[0]/Math.max(1,time))}})}
